package com.giodad.todolist.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class LibroAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLibroAllPropertiesEquals(Libro expected, Libro actual) {
        assertLibroAutoGeneratedPropertiesEquals(expected, actual);
        assertLibroAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLibroAllUpdatablePropertiesEquals(Libro expected, Libro actual) {
        assertLibroUpdatableFieldsEquals(expected, actual);
        assertLibroUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLibroAutoGeneratedPropertiesEquals(Libro expected, Libro actual) {
        assertThat(actual)
            .as("Verify Libro auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLibroUpdatableFieldsEquals(Libro expected, Libro actual) {
        assertThat(actual)
            .as("Verify Libro relevant properties")
            .satisfies(a -> assertThat(a.getTitolo()).as("check titolo").isEqualTo(expected.getTitolo()))
            .satisfies(a -> assertThat(a.getPrezzo()).as("check prezzo").isEqualTo(expected.getPrezzo()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLibroUpdatableRelationshipsEquals(Libro expected, Libro actual) {
        assertThat(actual)
            .as("Verify Libro relationships")
            .satisfies(a -> assertThat(a.getAutore()).as("check autore").isEqualTo(expected.getAutore()));
    }
}
