package com.giodad.todolist.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class RecensioneAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRecensioneAllPropertiesEquals(Recensione expected, Recensione actual) {
        assertRecensioneAutoGeneratedPropertiesEquals(expected, actual);
        assertRecensioneAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRecensioneAllUpdatablePropertiesEquals(Recensione expected, Recensione actual) {
        assertRecensioneUpdatableFieldsEquals(expected, actual);
        assertRecensioneUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRecensioneAutoGeneratedPropertiesEquals(Recensione expected, Recensione actual) {
        assertThat(actual)
            .as("Verify Recensione auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRecensioneUpdatableFieldsEquals(Recensione expected, Recensione actual) {
        assertThat(actual)
            .as("Verify Recensione relevant properties")
            .satisfies(a -> assertThat(a.getDescrizione()).as("check descrizione").isEqualTo(expected.getDescrizione()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRecensioneUpdatableRelationshipsEquals(Recensione expected, Recensione actual) {
        assertThat(actual)
            .as("Verify Recensione relationships")
            .satisfies(a -> assertThat(a.getLibro()).as("check libro").isEqualTo(expected.getLibro()));
    }
}
